#!/bin/bash
echo "Running Luacheck before commit..."
luacheck src
RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "[FAIL] Luacheck failed! Please fix errors before committing."
    exit 1
fi
echo "[SUCCESS] Luacheck passed!"
exit 0
