name: Auto-add to Project
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Data
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/h2-modpack/projects/1
          github-token: ${{ secrets.PROJECT_ADD_TOKEN }}
